Rakib1514/Tickto-Client

package-lock.json, package.json, src/pages/home/Reviews.jsx, src/styles.css
=> Update review section

src/main.jsx, src/pages/all-events/AllEvents.jsx
=> update: all events page. 

package-lock.json, package.json, src/pages/update-profile/UpdateProfile.jsx
=> Created Upadate profile

firebase.init.js, src/components/Shared/Navbar.jsx, src/dashboard/Chart.jsx, src/dashboard/Dashboard.jsx, src/dashboard/Dashboard_layout.jsx, src/dashboard/user/My_profile.jsx, src/index.css, src/pages/about-us/AboutUs.jsx, src/pages/home/Events.jsx, src/pages/home/Feature.jsx, src/pages/home/PopularNow.jsx, src/pages/home/RecentView.jsx, src/pages/home/Travel.jsx, src/routes/PrivateRoute.jsx, src/routes/PublicRoutes.jsx
=>  Dashboard Layout added

src/dashboard/Dashboard.jsx, src/dashboard/Dashboard_layout.jsx, src/dashboard/TotalRevenue.jsx, src/dashboard/admin/Add_event.jsx, src/dashboard/admin/Admin_dashboard.jsx, src/dashboard/admin/Booking_reports.jsx, src/dashboard/admin/Manage_tickets.jsx, src/dashboard/admin/Manage_user.jsx, src/dashboard/admin/Payment_reports.jsx, src/dashboard/admin/Setting.jsx, src/index.css, src/routes/PublicRoutes.jsx
Added admin important route to manage event ticket or booking system and setting this
=> Include add event amd admin dashboard

package-lock.json, package.json, src/dashboard/Dashboard.jsx, src/hooks/useAuth.jsx
created useAuth and useAxiosPublic custom hook
=> created useAuth and useAxiosPublic custom hook

src/components/Shared/SmallCard.jsx, src/layouts/MainLayout.jsx, src/pages/event-details/EventDetails.jsx
=> added: Event details page

src/dashboard/Dashboard.jsx, src/dashboard/admin/Manage_user.jsx
=> All user table

src/dashboard/Dashboard.jsx, src/layouts/MainLayout.jsx, src/pages/all-events/AllEvents.jsx
=> feat: data fetch & dashboard logo

src/dashboard/admin/Manage_user.jsx
=> Create handle make admin role

src/dashboard/admin/Manage_user.jsx
=> created handle user delete

src/Provider/AuthProvider.jsx, src/dashboard/admin/Manage_user.jsx
Updated auth provide get token and store client
=> Updated auth provide get token and store client

package-lock.json, package.json, src/Provider/AuthProvider.jsx, src/components/Shared/Navbar.jsx, src/dashboard/Dashboard.jsx, src/dashboard/admin/Manage_user.jsx, src/hooks/useAdmin.jsx, src/hooks/useAxiosSecure.jsx, src/pages/Auth/Register.jsx
created useAdmin custom hook and also make secure admin
=> created useAdmin custom hook

src/hooks/useAxiosPublic.jsx, src/hooks/useAxiosSecure.jsx, src/layouts/MainLayout.jsx, src/pages/all-events/AllEvents.jsx, src/pages/home/EidFeature.jsx
=> Changed baseURL

src/components/Shared/Navbar.jsx, src/hooks/useAdmin.jsx, src/hooks/useAxiosPublic.jsx, src/hooks/useAxiosSecure.jsx, src/layouts/MainLayout.jsx, src/pages/all-events/AllEvents.jsx
=> updated dashboard code

src/components/Shared/Footer.jsx, src/pages/payment/Payment.jsx
footer edit and payment page margin add #akash
=> footer edit and payment page margin add #akash

package-lock.json, package.json, src/main.jsx, src/routes/PublicRoutes.jsx
=> updates routes data mood

src/pages/payment/AllPaymentReports.jsx, src/pages/payment/PaymentHistory.jsx, src/routes/PublicRoutes.jsx
=> conflict issue #Akash

src/pages/Auth/Login.jsx, src/routes/PrivateRoute.jsx
[added]: google login redirect add
=> [added]: google login redirect add  #akash

src/components/PdfTicket.jsx, src/pages/payment/CheckoutForm.jsx
=> fix: pdf image add #akash

package-lock.json, package.json, src/Utils/AuthObserver.jsx, src/dashboard/Dashboard.jsx, src/hooks/useAxiosSecure.jsx, src/pages/Auth/Register.jsx
=> Fix: Login and Register error

src/components/Shared/Navbar.jsx, src/dashboard/Dashboard.jsx, src/pages/join-us/JoinUs.jsx
=> Update some UI
